version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/data/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Url_Shortener
      MYSQL_USER: chrischen
      MYSQL_PASSWORD: funnow
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - docker_net

  redis:
    image: redis:6.2.6
    volumes:
      - redis_data:/data/redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - docker_net

  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    command: ["sh", "./start.sh"]
    networks:
      - docker_net

networks:
  docker_net:
    driver: "bridge"

volumes:
  db_data:
  redis_data: